### ISSUE TITLE
Integration with passport.js or another security app.

### ISSUE THREAD

**Issue by hibyguy** [hibyguy/BTSwebsite#12]
Lets work with tokens and study them to make the work on the website

**Comment by hibyguy** [comment]
@jdegroot2797 make sure to do the same thing i mentioned on the code clean up bug #13

**Comment by jdegroot2797** [comment]
Passport js has been implemented to the user login credentials and session information. I have used bcrypt to encrypt the data and salting to sanitize. Upon launching this project build you will have to register a new account now that new security is in place. You will also notice that the database is no longer storing the raw credentials and now contains hashes in commit: 4de8818
